---
deployment:
  tasks:
    - export DEPLOYPATH=/home/isandybe/public_html/zenmind/
    - cp $DEPLOYPATH/db.php $DEPLOYPATH/db_live.php || true
    - /bin/cp -R * $DEPLOYPATH
    - cp $DEPLOYPATH/db_live.php $DEPLOYPATH/db.php || true
    - rm -f $DEPLOYPATH/db_live.php
